title: brodda.IT Tutorials
description: A random selection of notes/tutorials that have been created during my daily work.
theme: just-the-docs
source: content

url: https://janxb.github.io/tutorials

aux_links:
  brodda.IT: https://brodda.it

callouts:
  warning:
    color: yellow
  info:
    color: blue
  success:
    color: green
  note:
    color: purple
  danger:
    color: red